name: Extract Zip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          unzip xpose-1.21.8.zip -d .
          rm xpose-1.21.8.zip
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Extract zip into repo root"
          git push
